language: node_js
node_js:
- 0.10
before_script:
  - "npm install -g se-interpreter"
script:
  - "se-interpreter interpreter_config.json"

env:
  global:
    - SAUCE_USERNAME=sheikp
    - SAUCE_ACCESS_KEY=a48e19aa-39fa-4419-89f4-2af30746d0d1

language: python
python:
  - "2.7"
before_script:
  - chmod +x bin/JMeterInstaller.py
script:
  - nosetests -s
  - rm -rf results && mkdir results
  - apache-jmeter-2.13/bin/jmeter.sh -j results/jmeter.log -p tests/jmeter.properties -t tests/my_test_with_parameters.jmx -n -l results/my_test_with_parameters.jtl -Jserver=vzdispatchtest.azurewebsites.net
  - bin/generate_files_from_jtl.sh my_test_with_parameters
